language: node_js
dist: trusty
node_js:
- 12.4.0
env:
  global:
  - DBUS_SESSION_BUS_ADDRESS=/dev/null
  - DISPLAY=:99.0
  - CHROME_BIN=chromium-browser
before_script:
- sh -e /etc/init.d/xvfb start
install:
- npm install && npm install -g @angular/cli
script:
- npm run test
- npm run build:lib
sudo: required
before_deploy:
  if [[ $TRAVIS_TAG ]]; then
    cd dist/schema-form;
  else
    git config --global user.email "build@travis-ci.com";
    git config --global user.name "Travis CI";
    export PACKAGE_VERSION=$(npm run get_version | tail -n 1);
    if ! [ $(git tag -l "$PACKAGE_VERSION") ]; then
      echo "TAGGING $PACKAGE_VERSION...";
      export PUSH_TAG="ok";
      git tag $PACKAGE_VERSION;
    fi
  fi
deploy:
  - provider: releases
    api_key:
      secure: MYvXFlAVeaWcTuD+MjyFmwJJYXTKFZj8IjY3IhcqvW3EkSJK9BwdRXCGwcmAf5SI3uLXk9xf+t1uScV788frWcqL7jdRZQ04CpjbXuPkyXr+gqScLd9JHHlVTH+v8oAscXlOnyAnzfd+7uOsWLNaTdAzrSxhpnndR9Jw8l33VWl6DKQS3sfocx7YH/nqilOAj0KcF0yXEd1wjIRP7SNojIBFK6A1d/u0mZVRnVX58jeBgDKyl2TinuAJWA4iDBLziPgCvnPVOhTGSfc9m/YC/pAorq/yt74kLFBgKXoK979h927YUHxLTjZNJJhEM3XDRtf4ZJohfZcUs1BwdjYB8gKqV6yLGayQwyzfAkhvX7x93SwcZg/46zwPygzhHWkqX+//874N8RhK1duqYf0TU64K4vc/3fvYdX6cPjvr50u2lQyz3FaQ+QyKNStrk/7WkGkfHaTfFAO/arNEYnxc4/9PPXFy3I8CbFj3SIlc9CZHNZYzWb8NS8QHynAebqla4hcQjdOyi7TFWMqbmIRuynf+B8tCC093MJPjNadbZBdtTpRyO+y5dvD+qA2UBH5NLKHv9PBbi4Po8j9GAohxJPtBLdtGQPvtl64Z0cbAcuHO2o2/PXdtEBgflI/hSwFeK9Zb9GwgMFiBUySvLedoUJDjvKEDWSjvJVA8f92E8ew=
    name: Build $PACKAGE_VERSION
    on:
      repo: guillotinaweb/ngx-schema-form
      branch: master
      condition: $PUSH_TAG IS present
  - provider: npm
    edge: true
    email: ebrehault@gmail.com
    skip_cleanup: true
    api_key:
      secure: Qp/YeV/m9dpJ0vhrEi67qnzyik1CJbJMZr9lqQm9bHAsKTmMj+lQLDRvZ9bwoZy3F3+JHy7m8sdZyfVySr4F8kiI/EVEG2Qw0A89Xsi16L8XxPB8ycBiDnUYPVkwFHnfMG3e+UVW8mLrJkyyWnaSsy4fSjGnArt5bZcGmq4lxRHfWeoO5XU6731FEfMBdiDPQxCUHTFlSe0gRFVyx0wXSQ58RVTDk0OCnRCX0En8L4+Q2JqB6GOAF8N5KtsjN+h15oDoWqLayM2gidkBzET2eLvunPGpT7/6NV4q6Ds0HAglR7ZQLFwp5K4mdTYSBF2QY+FGofQ2hf6VTpWbBL0XCWRVU9W3Ma6dem1UYu3N2XX1K0ogrSRaAD1xy5HLcE5a5yubRRfCdh4fTHlM3OV0/VlfjYuE+QX8f7vT9axKrWdV8vuB68P0RrZb2BoJF124LWrg9h75bWCOxN3aJwxttEobvTqE2s+rCi4cR4Kb30uTPGXpZiY8JTT48YCFsFfulr1FGrzOKbGnCK6wmqrwHRAWHx8DfVbSHkEkzVxPf4mYbCCi+CS3FcAtZqSDYRhMzZvKV7YUf/e78jphBF5rswWR6GBzxTQ13hfg+Ai20tU6er+AJdI1NGvcrv/TZKLw5wWGvF6gKWoZedj7nL1EOoFJx7tVzVTlboXGOWkuQAw=
    on:
      tags: true
      repo: guillotinaweb/ngx-schema-form
      branch: master
